import React from 'react';
import { Metadata } from 'next';
import Breadcrumbs from '@/components/Breadcrumbs';

export const metadata: Metadata = {
  title: 'Financial & General Disclaimer',
  description: 'Disclaimer regarding financial calculations, estimates, and informational guidance on IndiaUseful.',
  alternates: {
    canonical: 'https://indiauseful.com/disclaimer'
  }
};

export default function DisclaimerPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-10 sm:px-6 lg:px-8 text-gray-800">
      <Breadcrumbs items={[{ label: 'Financial Disclaimer' }]} />
      <h1 className="text-3xl font-extrabold text-gray-900 mt-4">Disclaimer</h1>
      <p className="text-gray-400 text-xs mt-1">Important Legal and Financial Notice</p>

      <div className="mt-8 space-y-6 leading-relaxed text-sm sm:text-base">
        <div className="rounded-xl border border-amber-200 bg-amber-50/60 p-4 text-amber-900">
          <strong>Notice:</strong> IndiaUseful is an independent informational utility and is NOT a bank, Non-Banking Financial Company (NBFC), mutual fund distributor, SEBI-registered Investment Advisor, or chartered accountant firm.
        </div>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-2">1. No Financial or Investment Advice</h2>
          <p>
            The content, tools, projections, and estimates on IndiaUseful are intended strictly for educational and self-planning purposes. Projections generated by our SIP, FD, PPF, NPS, or EMI calculators do not represent guaranteed returns or official bank repayment schedules.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-2">2. Bank & Lender Nuances</h2>
          <p>
            Actual bank EMI numbers may differ slightly due to rounding conventions, broken-period interest, processing fees, GST on documentation, insurance bundle premiums, or reset frequencies on floating-rate repo-linked home loans (EBLR/RLLR). Always verify with your respective financial institution before executing loan or deposit contracts.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-2">3. Gold Rates & Jewellery Bills</h2>
          <p>
            Gold prices, bullion rates, and jewellery making charges vary across retailers and Indian state associations (such as All Kerala Gold and Silver Merchants Association - AKGSMA). Our gold calculators are designed to help you verify billing arithmetic and 3% GST calculation, not provide official bullion spot rates.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-2">4. Consult Professionals</h2>
          <p>
            For personal financial planning, tax filing under Section 80C/Section 115BAC, or legal decisions, please consult a certified financial planner (CFP), SEBI RIA, or Chartered Accountant (CA).
          </p>
        </section>
      </div>
    </div>
  );
}
